version: 2
updates:
  # JavaScript/TypeScript dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    reviewers:
      - "hangjegyzet/developers"
    labels:
      - "dependencies"
      - "javascript"
    groups:
      next:
        patterns:
          - "next"
          - "@next/*"
          - "eslint-config-next"
      react:
        patterns:
          - "react"
          - "react-*"
          - "@types/react*"
      testing:
        patterns:
          - "jest"
          - "@testing-library/*"
          - "playwright"
          - "@playwright/*"
      supabase:
        patterns:
          - "@supabase/*"
          - "supabase"
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    reviewers:
      - "hangjegyzet/devops"
    labels:
      - "dependencies"
      - "github-actions"

  # Docker dependencies (if any)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    reviewers:
      - "hangjegyzet/devops"
    labels:
      - "dependencies"
      - "docker"