name: Dependency Review

on:
  # Disabled - requires GitHub Advanced Security
  # pull_request:
  #   branches: [main, master, develop]
  workflow_dispatch:  # Only run manually if needed

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
          deny-licenses: GPL-3.0, AGPL-3.0
        continue-on-error: true  # Continue even if Advanced Security is not enabled
          
      - name: Check for vulnerable dependencies
        run: |
          npm audit --production --audit-level=moderate || true