name: Verify Build

on:
  push:
    branches: [ build/verify-github-actions ]

jobs:
  verify-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install --legacy-peer-deps
    
    - name: Create minimal env file
      run: |
        echo "Creating .env.local with minimal values for build"
        touch .env.local
        # Copy all env vars from the example or create minimal ones
        echo "NEXT_PUBLIC_SUPABASE_URL=https://placeholder.supabase.co" >> .env.local
        echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=placeholder-anon-key" >> .env.local
        echo "SUPABASE_SERVICE_ROLE_KEY=placeholder-service-key" >> .env.local
        echo "DATABASE_URL=postgresql://user:pass@localhost:5432/db" >> .env.local
        echo "DIRECT_URL=postgresql://user:pass@localhost:5432/db" >> .env.local
        echo "STRIPE_SECRET_KEY=sk_test_placeholder" >> .env.local
        echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_placeholder" >> .env.local
        echo "STRIPE_WEBHOOK_SECRET=whsec_placeholder" >> .env.local
        echo "SENDGRID_API_KEY=SG.placeholder" >> .env.local
        echo "SENDGRID_FROM_EMAIL=noreply@example.com" >> .env.local
        echo "NEXT_PUBLIC_APP_URL=http://localhost:3000" >> .env.local
        echo "GOOGLE_CLIENT_ID=placeholder.apps.googleusercontent.com" >> .env.local
        echo "GOOGLE_CLIENT_SECRET=placeholder-secret" >> .env.local
        echo "NEXTAUTH_URL=http://localhost:3000" >> .env.local
        echo "NEXTAUTH_SECRET=placeholder-nextauth-secret" >> .env.local
        echo "REDIS_URL=redis://localhost:6379" >> .env.local
        echo "SIMPLEPAY_MERCHANT=placeholder" >> .env.local
        echo "SIMPLEPAY_SECRET_KEY=placeholder" >> .env.local
        echo "BARION_POSKey=placeholder" >> .env.local
        echo "BARION_PUBLIC_KEY=placeholder" >> .env.local
        echo "BARION_API_URL=https://api.test.barion.com" >> .env.local
        echo "SENTRY_DSN=https://placeholder@sentry.io/0" >> .env.local
        echo "NEXT_PUBLIC_SENTRY_DSN=https://placeholder@sentry.io/0" >> .env.local
        echo "SENTRY_ORG=placeholder-org" >> .env.local
        echo "SENTRY_PROJECT=placeholder-project" >> .env.local
        echo "SENTRY_AUTH_TOKEN=placeholder-token" >> .env.local
        echo "DEEPGRAM_API_KEY=placeholder" >> .env.local
        echo "OPENAI_API_KEY=sk-placeholder" >> .env.local
        echo "CLAUDE_API_KEY=sk-ant-placeholder" >> .env.local
        echo "NODE_ENV=production" >> .env.local
        echo "SKIP_ENV_VALIDATION=false" >> .env.local
    
    - name: Build project
      run: |
        echo "Starting build with increased memory..."
        npm run build
      env:
        NODE_OPTIONS: '--max-old-space-size=4096'
        NEXT_TELEMETRY_DISABLED: 1
        CI: true
    
    - name: Build success
      if: success()
      run: |
        echo "✅ Build completed successfully!"
        echo "Build artifacts are ready"